"""fix datetime typo

Revision ID: 338d95f114f9
Revises: 68386017909e
Create Date: 2025-09-25 00:05:35.970959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '338d95f114f9'
down_revision = '68386017909e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
