"""fix autoincrement id

Revision ID: 67db35249440
Revises: 735f9c0ad8b6
Create Date: 2025-09-25 00:13:08.845189

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67db35249440'
down_revision = '735f9c0ad8b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
