"""fix body column type

Revision ID: 68613c59adb3
Revises: 67db35249440
Create Date: 2025-09-25 02:52:03.660128

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68613c59adb3'
down_revision = '67db35249440'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
