"""add message fields

Revision ID: 735f9c0ad8b6
Revises: 338d95f114f9
Create Date: 2025-09-25 00:10:17.080361

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '735f9c0ad8b6'
down_revision = '338d95f114f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
